services:
  - type: cron
    name: allegro-monitor-cron
    env: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: python main.py
    schedule: "0 */3 * * *"
